name: SonarQube Cloud Analysis

on:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  analysis:
    name: SonarQube Cloud Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarQube Cloud Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=serhii-bohdanov_orangehrm-playwright-automation
            -Dsonar.organization=serhii-bohdanov